applications/persona/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = 'persona_app'  #el wrapper de las urls de aqui

urlpatterns = [                         #indica que se trabaja con una vista generica
    path('', views.HomeView.as_view(), name="inicio"),    
    path('all_employes/', views.listAllEmployes.as_view(), name="listAllEmployees"),    
    path('edit_all_employes/', views.EditAllEmployees.as_view(), name="EditAllEmployees"),    
    path('all_employes_department/<name>/', views.listEmployesByArea.as_view(), name= "list_employees_by_area"),    
    path('all_employes_job/<job>/', views.listEmployesByJob.as_view()),    
    path('all_employes_kword/', views.listEmployesBykword.as_view()),    
    path('all_employes_habilities/', views.listEmployesByHabilities.as_view()),    
    path('detail_employes/<pk>', views.EmployeDetailView.as_view(), name= "detail_of_employee"),    
    path('create-employe/', views.EmployeCreateView.as_view(), name="CreateEmployee"),    
    path('success/', views.SucessViewRegistration.as_view(), name='correcto'),    
    path('update-employe/<pk>', views.UpdateEmployeView.as_view(), name='update_employe'),    
    path('delete-employe/<pk>', views.DeleteEmployeView.as_view(), name='delete_employe'),    
]

empleadoProyect/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #added when manages images, uses things from settings.local

applications/persona/models.py
from django.db import models

from applications.departamento.models import Departamento

from ckeditor.fields import RichTextField
# Create your models here.

class Habilidades(models.Model):

    hability = models.CharField("Habilidad",max_length=20)


    class Meta:
        verbose_name = "Habilidad" #this is the responsible of showing on the admin console the name chosen
        verbose_name_plural = "Habilidades empleados" #this is the responsible of showing on the admin console the name chosen


    def __str__(self):
        return self.hability



class Empleado(models.Model):
    jobs = (
        ("0", "Contador"),
        ("1", "Administrador"),
        ("2", "Economista"),
        ("3", "Otro"),
    )

    name = models.CharField("Nombre empleado",max_length=20)
    last_name = models.CharField("Apellido",max_length=15)
    full_name = models.CharField("Nombre completo",max_length=40,blank=True)
    job = models.CharField("Trabajo",max_length=2,choices=jobs)
    #LLave foranea con departamento
    department = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    #image = models.ImageField
    image = models.ImageField(upload_to="empleado",blank=True, null=True)

    #Because is a relation many to many * - *
    habilities = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()



    class Meta:
        verbose_name = "Persona" #this is the responsible of showing on the admin console the name chosen
        verbose_name_plural = "Personas" #this is the responsible of showing on the admin console the name chosen
        ordering = ["name"]


    def __str__(self):
        return "{}  de {}".format(self.name, self.department.name)

applications/persona/forms.py
from django import forms

from .models import Empleado

#Para dar un toque personalizado al crear un nuevo empleado

class EmployeeForm(forms.ModelForm):
    """Form definition for Employee."""

    class Meta:
        """Meta definition for Employeeform."""

        model = Empleado
        fields = (
            'name',
            'last_name',
            'job',
            'department',
            'image',
            'habilities',
        )

        widgets = {
            'habilities' : forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
from .models import Empleado

#Form de mi form personalizado
from.forms import EmployeeForm

from django.urls import reverse_lazy

class HomeView(TemplateView): #Vista encargada de mostrar la pagina de inicio
    template_name = "inicio.html"

class listAllEmployes(ListView):

    template_name = "persona/list__all_employes.html"
    model = Empleado  #trae todos los empleados
    paginate_by = 4
   # context_object_name = "empleados_list"

    #This works with the search input that its on the HTML 
    def get_queryset(self):
        key_word = self.request.GET.get("kword", "") #ese id lo puse yo 

        # if key_word == "":
        #     return Empleado.objects.all()   is one valid aproach

        return Empleado.objects.filter( name__icontains = key_word ) #if at least has one character of the Kword


class EditAllEmployees(ListView):

    template_name = "persona/edit_all_employes.html"
    model = Empleado  #trae todos los empleados
    paginate_by = 4
   # context_object_name = "empleados_list"

    #This works with the search input that its on the HTML 
    def get_queryset(self):
        key_word = self.request.GET.get("kword", "") #ese id lo puse yo 

        # if key_word == "":
        #     return Empleado.objects.all()   is one valid aproach

        return Empleado.objects.filter( name__icontains = key_word ) #if at least has one character of the Kword


class listEmployesByArea(ListView):
    
    template_name = "persona/list__all_by_area.html"

#metodo sobreescrito de la listView
    def get_queryset(self):
        area = self.kwargs["name"]
        return Empleado.objects.filter( department__name = area )


class listEmployesByJob(ListView):
    
    template_name = "persona/list__all_by_job.html"

    #metodo sobreescrito de la listView
    def get_queryset(self):
        jobQuery = self.kwargs["job"]
        return Empleado.objects.filter( job = jobQuery )

class listEmployesBykword(ListView):
    
    template_name = "persona/list__all_by_kword.html"

    #metodo sobreescrito de la listView
    def get_queryset(self):
        key_word = self.request.GET.get("kword", "") #ese id lo puse yo 
        return Empleado.objects.filter( name = key_word )

class listEmployesByHabilities(ListView):
    
    template_name = "persona/list__all_by_habilities.html"
    context_object_name = "habilidades"

    def get_queryset(self):
        key_word = self.request.GET.get("employee_search", "") #ese id lo puse yo 

        try:
            employee = Empleado.objects.get( name = key_word )
        except:
            print("No hubo request")
            return []

        return employee.habilities.all()

class EmployeDetailView(DetailView):
    model = Empleado
    template_name = "persona/employe_detail_view.html"

    # def get_context_data(self,**kwargs):
    #     context = super(EntryDetailView, self).get_context_data(**kwargs)
    #     context = ['Titulo'] = "Empleado del mes"
    #     return context

class SucessViewRegistration(TemplateView):
    template_name = "persona/success.html"

class EmployeCreateView(CreateView):
    model = Empleado
    template_name = "persona/create_employe_view.html"
    #fields = ['name','last_name','job','department','habilities','image',] ya no lo uso porque estoy usando forms
    #fields = ('__all__')
    #success_url = '.' #takes us to the same URL
    form_class = EmployeeForm
    success_url = reverse_lazy('persona_app:listAllEmployees')


    def form_valid(self,form): #This function is called when the data introduced into the template has beeen reconized as valid
        
        employee = form.save(commit = False)  #saves the data on the DB and assigns the data to this var , with commit False the save is aborted
        employee.full_name = employee.name + " " + employee.last_name
        employee.save() # updates the changes
        return super(EmployeCreateView,self).form_valid(form)

class UpdateEmployeView(UpdateView):
    model = Empleado
    template_name = "persona/update_view_employe.html"
    fields = ['name','last_name','job','department','habilities']
    success_url = reverse_lazy('persona_app:EditAllEmployees')


    #Antes de ser validados
    def post(self,request,*args,**kwargs):
        self.object = self.get_object()
        print(request.POST)
        return super().post(request,*args,**kwargs)

    #Despues de ser validados
    def form_valid(self,form): #This function is called when the data introduced into the template has beeen reconized as valid
        
        return super(UpdateEmployeView,self).form_valid(form)

class DeleteEmployeView(DeleteView):
    model = Empleado
    template_name = "persona/delete_employe_view.html"
    success_url = reverse_lazy('persona_app:EditAllEmployees')

    



 

templates/persona/create_employe_view.html
{% extends 'base.html' %}


{% block title %} Crear empleado {% endblock title %}

{% block content %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Creando empleado</h1>
        <!-- Pa guardar imagenes se usa el enctype -->
        <form class="cell" method="POST" enctype="multipart/form-data">{% csrf_token %} 
            {{form.as_p}}
            <div class="cell">
                <button type="submit" class="success button">Crear</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/delete_employe_view.html
{% extends 'base.html' %}


{% block title %} Eliminar empleado {% endblock title %}

{% block content %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{object.full_name}}</h1>

        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout alert">
                <h3>Eliminar</h3>
                <p>¿Seguro que desea eliminar?</p>
              </div>
            <div class="cell">
                <button type="submit" class="alert button">Borrar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/edit_all_employes.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Listado de empleados {% endblock title %}

{% block content %}


<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Editar empleados</h1>
        <!-- La parte de buscar -->
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-8">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>    
            <!-- El boton --> 
            <div class="cell large-4">

                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <!-- La tabla -->
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% if object_list %}
                        {% for employee in object_list %}
                            <tr>
                            <td>{{employee.id}}</td>
                            <td>{{employee.name}}</td>
                            <td>{{employee.last_name}}</td>
                            <td>{{employee.department.name}}</td>
                            <!-- Esto funciona en conjunto con la view de details view que recibe una pk en la url -->
                            <td>
                                <a href="{% url 'persona_app:update_employe' employee.id %}" class="button">Editar</a>
                                <a href="{% url 'persona_app:delete_employe' employee.id %}" class="button warning">Eliminar</a>
                            </td>
                            </tr>
                        {% endfor %}
                   {% endif %}
                </tbody>
              </table>
        </div>
        
        <!-- Paginacion -->
        <div  class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">

                  {% if page_obj.has_previous %}
                  <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Previous</a></li>
                    {% endif %}

                  <!-- <li><a href="#" aria-label="Page 2">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li> -->
                  {% for page in paginator.page_range%}
                    {% ifequal page page_obj.number %}
                    <li class="current"><span class="show-for-sr">Estas en pagina</span>{{page}}</li>
                    {% else %}
                    <li><a href="?page={{page}}" aria-label="Page 2">{{page}}</a></li>
                    {% endifequal %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                  <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a></li>
                 {% endif %}

                </ul>
              </nav>
            {% endif %}
        </div>
    </div>
    
</div>




{% endblock content %}

templates/persona/employe_detail_view.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Detalles empleado {% endblock title %}

{% block content %}

<div class="grid-container">
    <div class="grid-x align-center">
        <h1 class="cell">Detalles empleado: {{object.full_name}}</h1>
        <div class="card cell large-10" style="width: 500px;">
            <div class="card-divider">
                {{object.full_name}}
            </div>
            {% if object.image %}
                <img src="{{ object.image.url }}">
            {% else %}
                <!-- If an image doesnt exist in this employee -->
                <img src="{% static 'img/paris.jpg' %}"> 
            {% endif %}
            <div class="card-section">
              <h4>{{object.get_job_display}}</h4>
              <p>{{object.department.name}}</p>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                {% for hability in object.habilities.all %}
                   <li>{{hability}}</li>
                {% endfor %}
              </ul>
              <p>{{object.hoja_vida}}</p>
            </div>
          </div>
    </div>
</div>

{% endblock content %}

templates/persona/list__all_by_area.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Listado de empleados por area {% endblock title %}

{% block content %}

<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista de todos los empleados del area</h1>

        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% if object_list %}
                        {% for employee in object_list %}
                            <tr>
                            <td>{{employee.id}}</td>
                            <td>{{employee.name}}</td>
                            <td>{{employee.last_name}}</td>
                            <td>{{employee.department.name}}</td>
                            <!-- Esto funciona en conjunto con la view de details view que recibe una pk en la url -->
                            <td><a href="{% url 'persona_app:detail_of_employee' employee.id %}" class="button">Detalles</a></td>
                            </tr>
                        {% endfor %}
                   {% endif %}
                </tbody>
              </table>
        </div>

    </div>

</div>



{% endblock content %}





    {% for empleado in object_list %}

        <li> {{empleado}} </li>

    {% endfor %}

templates/persona/list__all_by_habilities.html
<h1>Habilidades wey</h1>


<form method="GET">{% csrf_token %}
    <input type="text" id="employee_search" name="employee_search" placeholder="Ingrese Nombre empleado">
    <button type="submit">Buscar</button>
</form>


<ul>
    {% for hability in habilidades %}

        <li> {{hability}} </li>

    {% endfor %}

</ul>

templates/persona/list__all_by_job.html
<h1>Lista empleados por trabajo</h1>

<ul>
    {% for empleado in object_list %}

        <li> {{empleado}} </li>

    {% endfor %}

</ul>

templates/persona/list__all_by_kword.html
<h1>Lista empleados por palabra</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese Nombre empleado">
    <button type="submit">Buscar</button>
</form>

<ul>
    {% for empleado in object_list %}

        <li> {{empleado}} </li>

    {% endfor %}

</ul>

templates/persona/list__all_employes.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Listado de empleados {% endblock title %}

{% block content %}


<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista de todos los empleados</h1>
        <!-- La parte de buscar -->
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-8">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>    
            <!-- El boton --> 
            <div class="cell large-4">

                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <!-- La tabla -->
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% if object_list %}
                        {% for employee in object_list %}
                            <tr>
                            <td>{{employee.id}}</td>
                            <td>{{employee.name}}</td>
                            <td>{{employee.last_name}}</td>
                            <td>{{employee.department.name}}</td>
                            <!-- Esto funciona en conjunto con la view de details view que recibe una pk en la url -->
                            <td><a href="{% url 'persona_app:detail_of_employee' employee.id %}" class="button">Detalles</a></td>
                            </tr>
                        {% endfor %}
                   {% endif %}
                </tbody>
              </table>
        </div>
        
        <!-- Paginacion -->
        <div  class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">

                  {% if page_obj.has_previous %}
                  <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Previous</a></li>
                    {% endif %}

                  <!-- <li><a href="#" aria-label="Page 2">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li> -->
                  {% for page in paginator.page_range%}
                    {% ifequal page page_obj.number %}
                    <li class="current"><span class="show-for-sr">Estas en pagina</span>{{page}}</li>
                    {% else %}
                    <li><a href="?page={{page}}" aria-label="Page 2">{{page}}</a></li>
                    {% endifequal %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                  <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a></li>
                 {% endif %}

                </ul>
              </nav>
            {% endif %}
        </div>
    </div>
    
</div>




{% endblock content %}

templates/persona/success.html
<h1>FELICIDADES PUÑETAS</h1>

templates/persona/update_view_employe.html
{% extends 'base.html' %}


{% block title %} Editar empleado {% endblock title %}

{% block content %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar weeee</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres
                        {{form.name}}
                    </label>
                  </div>
                <div class="cell large-6">
                    <label>Apellido
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento
                        {{form.department}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades
                        {{form.habilities}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Actualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content%}