applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'department_app' 


urlpatterns = [
    path('departamento_add/', views.NewDepartmentView.as_view(),name="crear_departamento"),
    path('list_all_departments/', views.ListAllDepartments.as_view(),name="listar_departamentos"),
    path('list_all_departments/<pk>', views.DepartmentDetailView.as_view(),name="detalle_departamentos"),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = 'persona_app'  #el wrapper de las urls de aqui

urlpatterns = [                         #indica que se trabaja con una vista generica
    path('', views.HomeView.as_view(), name="inicio"),    
    path('all_employes/', views.listAllEmployes.as_view(), name="listAllEmployees"),    
    path('edit_all_employes/', views.EditAllEmployees.as_view(), name="EditAllEmployees"),    
    path('all_employes_department/<name>/', views.listEmployesByArea.as_view(), name= "list_employees_by_area"),    
    path('all_employes_job/<job>/', views.listEmployesByJob.as_view()),    
    path('all_employes_kword/', views.listEmployesBykword.as_view()),    
    path('all_employes_habilities/', views.listEmployesByHabilities.as_view()),    
    path('detail_employes/<pk>', views.EmployeDetailView.as_view(), name= "detail_of_employee"),    
    path('create-employe/', views.EmployeCreateView.as_view(), name="CreateEmployee"),    
    path('success/', views.SucessViewRegistration.as_view(), name='correcto'),    
    path('update-employe/<pk>', views.UpdateEmployeView.as_view(), name='update_employe'),    
    path('delete-employe/<pk>', views.DeleteEmployeView.as_view(), name='delete_employe'),    
]

empleadoProyect/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #added when manages images, uses things from settings.local

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados<a href="/"></a></li>
        <li><a href="{% url 'persona_app:listAllEmployees' %}">Listar</a></li>
        <li><a href="{% url 'department_app:listar_departamentos' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:EditAllEmployees' %}">Administrar</a></li>
        <li><a href="{% url 'department_app:crear_departamento' %}">Crear departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar"></li>
        <li><a href="{% url 'persona_app:CreateEmployee' %}"  class="button">Registrar nuevo</a></li>
      </ul>
    </div>
  </div>