applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'department_app' 


urlpatterns = [
    path('departamento_add/', views.NewDepartmentView.as_view(),name="crear_departamento"),
    path('list_all_departments/', views.ListAllDepartments.as_view(),name="listar_departamentos"),
    path('list_all_departments/<pk>', views.DepartmentDetailView.as_view(),name="detalle_departamentos"),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = 'persona_app'  #el wrapper de las urls de aqui

urlpatterns = [                         #indica que se trabaja con una vista generica
    path('', views.HomeView.as_view(), name="inicio"),    
    path('all_employes/', views.listAllEmployes.as_view(), name="listAllEmployees"),    
    path('edit_all_employes/', views.EditAllEmployees.as_view(), name="EditAllEmployees"),    
    path('all_employes_department/<name>/', views.listEmployesByArea.as_view(), name= "list_employees_by_area"),    
    path('all_employes_job/<job>/', views.listEmployesByJob.as_view()),    
    path('all_employes_kword/', views.listEmployesBykword.as_view()),    
    path('all_employes_habilities/', views.listEmployesByHabilities.as_view()),    
    path('detail_employes/<pk>', views.EmployeDetailView.as_view(), name= "detail_of_employee"),    
    path('create-employe/', views.EmployeCreateView.as_view(), name="CreateEmployee"),    
    path('success/', views.SucessViewRegistration.as_view(), name='correcto'),    
    path('update-employe/<pk>', views.UpdateEmployeView.as_view(), name='update_employe'),    
    path('delete-employe/<pk>', views.DeleteEmployeView.as_view(), name='delete_employe'),    
]

empleadoProyect/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #added when manages images, uses things from settings.local

applications/departamento/models.py
from django.db import models

# Create your models here.
# se crea el codigo python del modelo y la ORM se encarga de pasar todo eso a SQL
class Departamento(models.Model):
    name = models.CharField("Nombre",max_length=20)
    short_name = models.CharField("Nombre corto",max_length=15)
    active = models.BooleanField("Activo", default= False)

    class Meta:
        verbose_name = "Mi departamento" #this is the responsible of showing on the admin console the name chosen
        verbose_name_plural = "Semos muchos deps" #this is the responsible of showing on the admin console the name chosen
        ordering = ["-name"]
        unique_together = ("name","short_name")


    def __str__(self):
        return "{}  : is active {}".format(self.name, self.active)

applications/departamento/forms.py
from django import forms

from .models import Departamento


class NewDepartmentForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render

from .forms import NewDepartmentForm
from .models import Departamento


from django.views.generic.edit import (
    FormView,
)

from django.views.generic import (
    ListView,
    DetailView,
)

from applications.persona.models import Empleado
from .models import Departamento

from django.urls import reverse_lazy

class NewDepartmentView(FormView):
    template_name = "departamento/new_department_add.html"
    form_class = NewDepartmentForm
    success_url = "/"

    def form_valid(self, form):
        #one way to create an object
        dept = Departamento(
            name = form.cleaned_data ["departamento"],
            short_name = form.cleaned_data ["shorname"] #The data from the forms that i did
        )
        dept.save()
        #if I use this way save is mandatory

        name = form.cleaned_data ["nombre"]
        last_name = form.cleaned_data ["apellido"]

        #ORM one way to create an object, .save() is not neccesary if using create
        Empleado.objects.create(
            name = name,
            last_name = last_name,
            job = '1',
            department = dept
        )

        return super(NewDepartmentView,self).form_valid(form)

class ListAllDepartments(ListView):
    template_name = "departamento/list_all_departments.html"
    model = Departamento
    paginate_by = 4

        #This works with the search input that its on the HTML 
    def get_queryset(self):
        key_word = self.request.GET.get("kword", "") #ese id lo puse yo 

        # if key_word == "":
        #     return Empleado.objects.all()   is one valid aproach

        return Departamento.objects.filter( name__icontains = key_word ) #if at least has one character of the Kword

class DepartmentDetailView(DetailView):
    model = Departamento
    template_name = "departamento/detail_departments.html"

templates/departamento/detail_departments.html
<h1>Detalles weee</h1>

{{object}}

<p>{{object.name}}</p>
<p>{{object.short_name}}</p>

templates/departamento/list_all_departments.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Listado de departamentos {% endblock title %}

{% block content %}

<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista de todos los departamentos</h1>
        <!-- La parte de buscar -->
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-8">
                <input type="text" id="kword" name="kword" placeholder="Buscar departamento">
            </div>    
            <!-- El boton --> 
            <div class="cell large-4">

                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <!-- La tabla -->
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">Nombre</th>
                    <th>Nombre corto</th>
                    <th width="150">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    {% if object_list %}
                        {% for dep in object_list %}
                            <tr>
                            <td>{{dep.name}}</td>
                            <td>{{dep.short_name}}</td>
                            <!-- Esto funciona en conjunto con la view de details view que recibe una pk en la url -->
                            <td><a href="{% url 'persona_app:list_employees_by_area' dep.name %}" class="button">Ver empleados</a></td>
                            </tr>
                        {% endfor %}
                   {% endif %}
                </tbody>
              </table>
        </div>
        
        <!-- Paginacion -->
        <div  class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">

                  {% if page_obj.has_previous %}
                  <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Previous</a></li>
                    {% endif %}

                  <!-- <li><a href="#" aria-label="Page 2">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li> -->
                  {% for page in paginator.page_range%}
                    {% ifequal page page_obj.number %}
                    <li class="current"><span class="show-for-sr">Estas en pagina</span>{{page}}</li>
                    {% else %}
                    <li><a href="?page={{page}}" aria-label="Page 2">{{page}}</a></li>
                    {% endifequal %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                  <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a></li>
                 {% endif %}

                </ul>
              </nav>
            {% endif %}
        </div>
    </div>
    
</div>

{% endblock content %}

templates/departamento/new_department_add.html
{% extends 'base.html' %}


{% block title %} Crear departamento {% endblock title %}

{% block content %}

<div class="grid-container">
    <div class="grid-x">
        <div class="callout primary cell">
        <h1 class="cell">Creando Departamento</h1>
        <form class="cell" method="POST">{% csrf_token %}
            <h3>Datos empleado</h3>
            <p>
                Nombre
                {{form.nombre}}
            </p>
            <p>
                Apellido
                {{form.apellido}}
            </p>
            <h3>Datos Departamento</h3>
            <p>
                Departamento
                {{form.departamento}}
            </p>
            <p>
                Nombre corto
                {{form.shorname}}
            </p>
            <div class="cell">
                <button type="submit" class="success button cell large-12">Crear</button>
            </div>
        </form>
        </div>
    </div>
</div>

{% endblock content %}